# Generated by Django 5.1.5 on 2025-01-31 17:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'character',
            },
        ),
        migrations.CreateModel(
            name='TrainingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_messages', to='bot_app.character')),
            ],
            options={
                'db_table': 'training_message',
            },
        ),
        migrations.CreateModel(
            name='BotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.CharField(blank=True, max_length=50, null=True)),
                ('response', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_app.character')),
                ('training_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.trainingmessage')),
            ],
            options={
                'db_table': 'bot_response',
            },
        ),
    ]
